/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;
import proyecto.TableroStratego;
/**
 *
 * @author Administrator
 */

public class Batallas extends javax.swing.JFrame {
  DatosUsuario datos;
    Login login;
    Menu menu;
    UniversoMarvel marvel;
 private TableroStratego tablero;
    /**
     * Creates new form Batallas
     */
    public Batallas(DatosUsuario datos,Login login) {
        initComponents();
         setLocationRelativeTo(this);
         this.datos = datos;
         this.login=login;
        
         mostrarUsuariosActivos();
         marvel=new UniversoMarvel(login,datos);    
    }
    
    
    
 public void mostrarUsuariosActivos(){
     int usuariosActivos;
     int usuariosEliminados;
     usuariosActivos=datos.getListaUsuarios().size()-datos.getListaUsuariosEliminado().size();
     usuariosEliminados=datos.getListaUsuariosEliminado().size();
     
     lblCantUsuariosActivos.setText("Usuarios Activos: "+String.valueOf(usuariosActivos));
     lblCantUsuariosHistoricos.setText("Usuarios Historicos: "+String.valueOf(usuariosEliminados+usuariosActivos));
       lblCantGanadasHeroes.setText("Victorias Héroes: " + TableroStratego.contadorVictoriasHeroes);
    lblCantGanadasVillanos.setText("Victorias Villanos: " + TableroStratego.contadorVictoriasVillanos);

  
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCantUsuariosActivos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCantUsuariosHistoricos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCantGanadasHeroes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCantGanadasVillanos = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Batallas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 180, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("1. Usuarios Activos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, -1));

        lblCantUsuariosActivos.setForeground(new java.awt.Color(153, 0, 0));
        lblCantUsuariosActivos.setText("jLabel3");
        jPanel1.add(lblCantUsuariosActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 185, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("2. Usuarios Historicos: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 250, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("3. Cantidad Partidas Jugadas: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 330, -1));

        lblCantUsuariosHistoricos.setForeground(new java.awt.Color(153, 0, 0));
        lblCantUsuariosHistoricos.setText("jLabel5");
        jPanel1.add(lblCantUsuariosHistoricos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText(" a. Cantidad Veces Ganadas Heroes:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 320, -1));

        lblCantGanadasHeroes.setForeground(new java.awt.Color(153, 0, 0));
        lblCantGanadasHeroes.setText("jLabel6");
        jPanel1.add(lblCantGanadasHeroes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 160, 20));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("b. Cantidad Veces Ganadas Villanos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 330, -1, -1));

        lblCantGanadasVillanos.setForeground(new java.awt.Color(153, 0, 0));
        lblCantGanadasVillanos.setText("jLabel7");
        jPanel1.add(lblCantGanadasVillanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 170, 20));

        btnBack.setBackground(new java.awt.Color(153, 0, 0));
        btnBack.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("SALIR");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 375, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sin2.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          marvel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantGanadasHeroes;
    private javax.swing.JLabel lblCantGanadasVillanos;
    private javax.swing.JLabel lblCantUsuariosActivos;
    private javax.swing.JLabel lblCantUsuariosHistoricos;
    // End of variables declaration//GEN-END:variables
}
