
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class EliminarCuenta extends javax.swing.JFrame {

     DatosUsuario datos;
     Usuarios usuario;
     Login login;
     MiPerfil perfil;
     Menu menu;
     
    public EliminarCuenta(Login login) {
        initComponents();
        setLocationRelativeTo(this);
        this.login=login;
        datos=login.getDatos();
         perfil=new MiPerfil(login,datos);  
        menu=new Menu(login,datos);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        TextContra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eliminar Cuenta ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 122, 381, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("Username: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 130, -1));

        btnEliminar.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 330, 140, 38));

        btnCancel.setBackground(new java.awt.Color(153, 0, 0));
        btnCancel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCELAR");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 130, 38));
        jPanel1.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 240, -1));
        jPanel1.add(TextContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (TextUsuario.getText().isEmpty() || TextContra.getText().isEmpty() ) {
        JOptionPane.showMessageDialog(null, "Llene todos los campos.");
    } else {
           String username = TextUsuario.getText();
           String password = TextContra.getText();
           String eliminar = TextUsuario.getText()+"(-Eliminada)-";
           
                 
            // Buscar el usuario en los datos existentes
            Usuarios usuario = login.getDatos().buscarUsuario(username);
            
            if (usuario!= null) {
                if(username.equals(String.valueOf(this.datos.UsuarioLogeado))){
                if (usuario.getPassword().equals(password)) {
                    // Elimina el Usuario agregandole un "Eliminar"
                    usuario.setUsername(eliminar);
                    login.getDatos().agregarUsuarioEliminado(usuario);
                    
                    JOptionPane.showMessageDialog(null, "El Usuario Fue Eliminado Exitosamente");
                    login.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "La contraseña actual no es correcta.");
                }
                 }else{
                       JOptionPane.showMessageDialog(null, "Debe ser el usuario LOGGED IN");  
                 }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario no existe.");
            } 
}// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
 // TODO add your handling code here:
         MiPerfil perfil = new MiPerfil(login,datos);
    perfil.setVisible(true);
    this.dispose();        
    }//GEN-LAST:event_btnCancelActionPerformed

                                       

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextContra;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
