/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {

    DatosUsuario datos;
    public boolean esTutorial;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(818, 538);
        setLocationRelativeTo(this);
        this.datos=new DatosUsuario();
    }
    
    public DatosUsuario getDatos(){
        return datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnCreatePlayer = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(370, 200, 220, 30);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(370, 260, 220, 30);

        btnCreatePlayer.setBackground(new java.awt.Color(116, 14, 0));
        btnCreatePlayer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCreatePlayer.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePlayer.setText("Create Player");
        btnCreatePlayer.setBorderPainted(false);
        btnCreatePlayer.setFocusPainted(false);
        btnCreatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePlayerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreatePlayer);
        btnCreatePlayer.setBounds(420, 320, 130, 40);

        btnLogin.setBackground(new java.awt.Color(116, 14, 0));
        btnLogin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(250, 320, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnCreatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePlayerActionPerformed
        // TODO add your handling code here:
        Create_Player player=new Create_Player(this);
        player.setVisible(true);
         txtUsername.setText("");
         txtPassword.setText("");
        this.dispose();
    }//GEN-LAST:event_btnCreatePlayerActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        esTutorial=true;
        //Validacion no dejar espacios vacios
         if (txtUsername.getText().isEmpty()||txtPassword.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Llene todos los campos.");
    } else {
        String username=txtUsername.getText();
        String password=txtPassword.getText();
        
        Usuarios user=datos.buscarUsuario(username);
        //validacion de usuario y contrasena para luego abrir menu principal
        if(user !=null){
            if(user.getPassword().equals(password)){
                Menu menu=new Menu(this,datos);
                menu.setVisible(true);
                this.datos.UsuarioLogeado=username;
                txtUsername.setText("");
                txtPassword.setText("");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "La contrasena es incorrecta");
            }
        }else{
            JOptionPane.showMessageDialog(null, "El username no existe");
        }
         }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePlayer;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
