/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Menu extends javax.swing.JFrame {
    DatosUsuario datos;
    Login login;
    MiPerfil perfil;
    UniversoMarvel marvel;
 //  private MarvelStratego stratego;
    
   
    /**
     * Creates new form Menu
     */
    public Menu(Login login,DatosUsuario datos) {
        initComponents();
        this.setSize(818, 538);
        setLocationRelativeTo(this);
        this.login=login; 
        this.datos=datos;
     
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPartidadNueva = new javax.swing.JButton();
        btnMiPerfil = new javax.swing.JButton();
        btnUniversoMarvel = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPartidadNueva.setBackground(new java.awt.Color(225, 74, 53));
        btnPartidadNueva.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnPartidadNueva.setForeground(new java.awt.Color(255, 255, 255));
        btnPartidadNueva.setText("PARTIDA NUEVA");
        btnPartidadNueva.setBorder(null);
        btnPartidadNueva.setBorderPainted(false);
        btnPartidadNueva.setFocusPainted(false);
        btnPartidadNueva.setFocusable(false);
        btnPartidadNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidadNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPartidadNueva);
        btnPartidadNueva.setBounds(300, 160, 200, 30);

        btnMiPerfil.setBackground(new java.awt.Color(225, 74, 53));
        btnMiPerfil.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnMiPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnMiPerfil.setText("MI PERFIL");
        btnMiPerfil.setBorder(null);
        btnMiPerfil.setBorderPainted(false);
        btnMiPerfil.setFocusPainted(false);
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnMiPerfil);
        btnMiPerfil.setBounds(310, 220, 170, 30);

        btnUniversoMarvel.setBackground(new java.awt.Color(225, 74, 53));
        btnUniversoMarvel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnUniversoMarvel.setForeground(new java.awt.Color(255, 255, 255));
        btnUniversoMarvel.setText("UNIVERSO MARVEL");
        btnUniversoMarvel.setBorder(null);
        btnUniversoMarvel.setBorderPainted(false);
        btnUniversoMarvel.setFocusPainted(false);
        btnUniversoMarvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniversoMarvelActionPerformed(evt);
            }
        });
        getContentPane().add(btnUniversoMarvel);
        btnUniversoMarvel.setBounds(300, 290, 200, 20);

        btnCerrarSesion.setBackground(new java.awt.Color(116, 14, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion);
        btnCerrarSesion.setBounds(310, 350, 170, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sesión?", "Confirmación de cierre de sesión", JOptionPane.OK_CANCEL_OPTION);
    if (respuesta == JOptionPane.OK_OPTION) {
        login.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        // TODO add your handling code here:
        perfil=new MiPerfil(login,datos);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMiPerfilActionPerformed

    private void btnPartidadNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidadNuevaActionPerformed
        // TODO add your handling code here:
      SegundoPlayer pedirsegundo = new SegundoPlayer(login,datos);
        pedirsegundo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartidadNuevaActionPerformed

    private void btnUniversoMarvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniversoMarvelActionPerformed
        // TODO add your handling code here:
        marvel=new UniversoMarvel(login,datos);
        marvel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUniversoMarvelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMiPerfil;
    private javax.swing.JButton btnPartidadNueva;
    private javax.swing.JButton btnUniversoMarvel;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
