/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

/**
 *
 * @author Administrator
 */
public class MiPerfil extends javax.swing.JFrame {
    DatosUsuario datos;
    Menu menu;
    CambiarPassword cambiarPassword;
    EliminarCuenta EliminarCuenta;
    Login login;
    Logs logs;
    
    /**
     * Creates new form MiPerfil
     */
    public MiPerfil(Login login,DatosUsuario datos) {
        initComponents();
        setLocationRelativeTo(this);
        this.datos=datos;
        this.login=login;
        menu=new Menu(login,datos);
        mostrarRanking();
         lblUsuarioLogeado.setText(datos.UsuarioLogeado);
    }
    
     private void mostrarRanking() {
         StringBuilder ranking = new StringBuilder();
    Usuarios usuarioLogeado = datos.buscarUsuario(datos.UsuarioLogeado);

    if (usuarioLogeado != null) {
        ranking.append(usuarioLogeado.getPuntos()).append(" puntos\n");
    }
    lblPuntos.setText(ranking.toString());
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogUltimosJuegos = new javax.swing.JButton();
        btnCambiarPassword = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblUsuarioLogeado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mi Perfil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 180, 40));

        btnLogUltimosJuegos.setBackground(new java.awt.Color(153, 0, 0));
        btnLogUltimosJuegos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnLogUltimosJuegos.setForeground(new java.awt.Color(255, 255, 255));
        btnLogUltimosJuegos.setText("LOG DE MIS JUEGOS");
        btnLogUltimosJuegos.setBorder(null);
        btnLogUltimosJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogUltimosJuegosActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogUltimosJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 340, 30));

        btnCambiarPassword.setBackground(new java.awt.Color(153, 0, 0));
        btnCambiarPassword.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCambiarPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarPassword.setText("CAMBIAR CONTRASEÑA");
        btnCambiarPassword.setBorder(null);
        btnCambiarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 286, 340, 30));

        btnEliminarCuenta.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarCuenta.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCuenta.setText("ELIMINAR CUENTA");
        btnEliminarCuenta.setActionCommand("ELIMINAR CUENTA");
        btnEliminarCuenta.setBorder(null);
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 340, 30));

        btnBack.setBackground(new java.awt.Color(204, 0, 0));
        btnBack.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("SALIR");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 120, 40));

        lblUsuarioLogeado.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblUsuarioLogeado.setForeground(new java.awt.Color(153, 0, 51));
        lblUsuarioLogeado.setText("jLabel2");
        jPanel1.add(lblUsuarioLogeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 109, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Puntos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 78, -1));

        lblPuntos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(153, 0, 51));
        lblPuntos.setText("Puntos");
        jPanel1.add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sin2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogUltimosJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogUltimosJuegosActionPerformed
    Logs logs = new Logs(login, datos);
    logs.setVisible(true);
    this.dispose();      
    }//GEN-LAST:event_btnLogUltimosJuegosActionPerformed

    private void btnCambiarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPasswordActionPerformed
        // TODO add your handling code here:
        cambiarPassword=new CambiarPassword(login);
        cambiarPassword.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCambiarPasswordActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
          EliminarCuenta llamar =new EliminarCuenta(login);
        llamar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCambiarPassword;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnLogUltimosJuegos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblUsuarioLogeado;
    // End of variables declaration//GEN-END:variables
}
